Search.appendIndex(
    [
                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker",
            "name": "AccessChecker",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003AgetGlobalAuthorizable\u0028\u0029",
            "name": "getGlobalAuthorizable",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#method_getGlobalAuthorizable"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003AgetUser\u0028\u0029",
            "name": "getUser",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#method_getUser"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003AcheckAccess\u0028\u0029",
            "name": "checkAccess",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#method_checkAccess"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003ATARGET_PARAM",
            "name": "TARGET_PARAM",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#constant_TARGET_PARAM"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003AGLOBAL",
            "name": "GLOBAL",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#constant_GLOBAL"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003AGUEST",
            "name": "GUEST",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#constant_GUEST"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003ABUILTIN",
            "name": "BUILTIN",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#constant_BUILTIN"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003A\u0024manager",
            "name": "manager",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#property_manager"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003A\u0024globalName",
            "name": "globalName",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#property_globalName"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003A\u0024globalId",
            "name": "globalId",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#property_globalId"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003A\u0024guestId",
            "name": "guestId",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#property_guestId"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003A\u0024guestName",
            "name": "guestName",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#property_guestName"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003A\u0024userClass",
            "name": "userClass",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#property_userClass"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\AccessChecker\u003A\u003A\u0024userCache",
            "name": "userCache",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-AccessChecker.html#property_userCache"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository",
            "name": "ActiveRecordRepository",
            "summary": "Class\u0020ActiveRecordRepository\nStore\u0020permissions\u0020in\u0020an\u0020ActiveRecord\u0020model",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "PermissionRepository\u0020constructor.",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository\u003A\u003Agrant\u0028\u0029",
            "name": "grant",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html#method_grant"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository\u003A\u003Arevoke\u0028\u0029",
            "name": "revoke",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html#method_revoke"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository\u003A\u003Acheck\u0028\u0029",
            "name": "check",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html#method_check"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository\u003A\u003Asearch\u0028\u0029",
            "name": "search",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html#method_search"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository\u003A\u003ASOURCE_ID",
            "name": "SOURCE_ID",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html#constant_SOURCE_ID"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository\u003A\u003ASOURCE_NAME",
            "name": "SOURCE_NAME",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html#constant_SOURCE_NAME"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository\u003A\u003ATARGET_ID",
            "name": "TARGET_ID",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html#constant_TARGET_ID"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository\u003A\u003ATARGET_NAME",
            "name": "TARGET_NAME",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html#constant_TARGET_NAME"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository\u003A\u003APERMISSION",
            "name": "PERMISSION",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html#constant_PERMISSION"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository\u003A\u003A\u0024modelClass",
            "name": "modelClass",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html#property_modelClass"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordRepository\u003A\u003A\u0024attributeMap",
            "name": "attributeMap",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordRepository.html#property_attributeMap"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordResolver",
            "name": "ActiveRecordResolver",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordResolver.html"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordResolver\u003A\u003AfromSubject\u0028\u0029",
            "name": "fromSubject",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordResolver.html#method_fromSubject"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\ActiveRecordResolver\u003A\u003AtoSubject\u0028\u0029",
            "name": "toSubject",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-ActiveRecordResolver.html#method_toSubject"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\PermissionValidator",
            "name": "PermissionValidator",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-PermissionValidator.html"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\PermissionValidator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-PermissionValidator.html#method___construct"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\PermissionValidator\u003A\u003AvalidateValue\u0028\u0029",
            "name": "validateValue",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-PermissionValidator.html#method_validateValue"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\PermissionValidator\u003A\u003A\u0024field",
            "name": "field",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-PermissionValidator.html#property_field"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\PermissionValidator\u003A\u003A\u0024allowArray",
            "name": "allowArray",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-PermissionValidator.html#property_allowArray"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\PermissionValidator\u003A\u003A\u0024permissionName",
            "name": "permissionName",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-PermissionValidator.html#property_permissionName"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\PermissionValidator\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-PermissionValidator.html#property_query"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\PermissionValidator\u003A\u003A\u0024accessChecker",
            "name": "accessChecker",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-PermissionValidator.html#property_accessChecker"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac\\PermissionValidator\u003A\u003A\u0024source",
            "name": "source",
            "summary": "",
            "url": "classes/SamIT-Yii2-abac-PermissionValidator.html#property_source"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\SamIT\\Yii2\\abac",
            "name": "abac",
            "summary": "",
            "url": "namespaces/samit-yii2-abac.html"
        },                {
            "fqsen": "\\SamIT\\Yii2",
            "name": "Yii2",
            "summary": "",
            "url": "namespaces/samit-yii2.html"
        },                {
            "fqsen": "\\SamIT",
            "name": "SamIT",
            "summary": "",
            "url": "namespaces/samit.html"
        }            ]
);
